-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 05:30:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cl1_MarcoArandaMauricio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cl1_MarcoArandaMauricio` ;

-- -----------------------------------------------------
-- Schema Cl1_MarcoArandaMauricio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cl1_MarcoArandaMauricio` DEFAULT CHARACTER SET utf8 ;
USE `Cl1_MarcoArandaMauricio` ;

-- -----------------------------------------------------
-- Table `Cl1_MarcoArandaMauricio`.`especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cl1_MarcoArandaMauricio`.`especialidad` ;

CREATE TABLE IF NOT EXISTS `Cl1_MarcoArandaMauricio`.`especialidad` (
  `idesp` INT NOT NULL,
  `nomesp` VARCHAR(45) NULL,
  `costo` DECIMAL(4) NULL,
  PRIMARY KEY (`idesp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cl1_MarcoArandaMauricio`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cl1_MarcoArandaMauricio`.`alumno` ;

CREATE TABLE IF NOT EXISTS `Cl1_MarcoArandaMauricio`.`alumno` (
  `idalumno` VARCHAR(45) UNIQUE,
  `apealumno` VARCHAR(45) NULL,
  `nomalumno` VARCHAR(45) NULL,
  `idesp` INT NULL,
  `proce` VARCHAR(45) NULL,
  PRIMARY KEY (`idalumno`),
  CONSTRAINT `idesp`
    FOREIGN KEY (`idesp`)
    REFERENCES `Cl1_MarcoArandaMauricio`.`especialidad` (`idesp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `Cl1_MarcoArandaMauricio`.`especialidad` (`idesp`, `nomesp`, `costo`) VALUES ('1', 'Matematicas', 12.5); INSERT INTO `Cl1_MarcoArandaMauricio`.`especialidad` (`idesp`, `nomesp`, `costo`) VALUES ('2', 'Programacion', 100.20);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
